name: Validar Compilação (C)

on:
  pull_request:
    branches: ["develop"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc
      - name: Validar arquivos de código por pasta
        shell: bash
        run: |

            echo "Validando arquivos na pasta $folder..."
            
            # Verifica se existem arquivos .h na pasta
            if ls "$folder"*.h >/dev/null 2>&1; then
              echo "Compilando todos os arquivos .c na pasta $folder..."

              if gcc "$folder"*.c -o "$folder/a.out" -lm; then
                echo "✅ Pasta $folder compilada com sucesso!"
              else
                echo "❌ Erro ao compilar a pasta $folder"
                exit 1
              fi
            else

                echo "Compilando $file..."
                if gcc "$file" -o "${file%.c}.out" -lm; then
                  echo "✅ Arquivo $file compilado com sucesso!"
                else
                  echo "❌ Erro ao compilar o arquivo $file"
                  exit 1
                fi
              done
            fi
          done
